routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
// use Illuminate\Routing\Route;

Route::get('/', function () {
    return view('welcome');
});


Route::resource('projects', 'ProjectController');
Route::resource('tasks', 'TaskController');
Route::put('tasks/{id}/done', 'TaskController@done')->name('tasks.done');

Auth::routes();

Route::get('/home', 'ProjectController@index')->name('home');

Auth::routes();

Route::get('/home', 'ProjectController@index')->name('home');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
}

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Project;
use \App\Task;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class ProjectController extends Controller
{
    public function index(Request $req)
    {
        $user = Auth::user();
        $projects = Project::where('id_user', $user->id)->orderBy('id', 'desc')->get();
        return view('projects.index', compact('projects'));
    }

    public function create()
    {
        return view('projects.create');
    }

    public function store(Request $request)
    {
        $user = Auth::user();

        $validasi = $request->validate([
            'nama' => 'required|max:255',
            'mulai' => 'required',
            'target' => 'required',
        ]);


        $nama = $request['nama'];
        $mulai = $request['mulai'];
        $target = $request['target'];

        $project = new Project();
        $project->id_user = $user->id;
        $project->nama = $nama;
        $project->tanggal_mulai = $mulai;
        $project->tanggal_target = $target;
        $project->created_at = now();
        $project->updated_at = now();
        $project->save();

        return redirect('projects');
    }

    public function show($id)
    {
        $project = Project::find($id);
        $user = Auth::user();

        if ($project->id_user != $user->id) {
            return redirect('projects');
        }

        $tasks = Task::where('project_id', $id)->get();
        return view('projects.show', compact('project', 'tasks'));
    }

    public function edit($id)
    {
        $project = Project::find($id);

        $user = Auth::user();

        if ($project->id_user != $user->id) {
            return redirect('projects');
        }

        return view('projects.edit', compact('project'));
    }

    public function update(Request $request, $id)
    {
        $project = Project::find($id);
        $validasi = $request->validate([
            'nama' => 'required|max:255',
            'mulai' => 'required',
            'target' => 'required',
        ]);

        $project->nama = $request->nama;
        $project->tanggal_mulai = $request->mulai;
        $project->tanggal_target = $request->target;
        $project->updated_at = now();
        $project->save();

        return redirect('projects');
    }

    public function destroy($id)
    {
        $project = Project::find($id);

        $user = Auth::user();

        if ($project->id_user != $user->id) {
            return redirect('projects');
        }

        $task = Task::where('project_id', $id)->delete();

        $project->delete();

        return redirect('projects');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
// use \App\Project;
use \App\Task;

class TaskController extends Controller
{
    // public function index()
    // {
    //     $projects = Project::orderBy('id', 'desc')->get();
    //     return view('projects.index', compact('projects'));
    // }

    public function create()
    {
        return view('tasks.create');
    }

    public function store(Request $request)
    {
        $validasi = $request->validate([
            'nama' => 'required|max:255',
            'mulai' => 'required',
            'target' => 'required',
            'id' => 'required',
            'keterangan' => 'required',
        ]);

        $nama = $request['nama'];
        $mulai = $request['mulai'];
        $target = $request['target'];
        $keterangan = $request['keterangan'];
        $id = $request['id'];

        $task = new Task();
        $task->nama = $nama;
        $task->keterangan = $keterangan;
        $task->done = 0;
        $task->tanggal_mulai = $mulai;
        $task->tanggal_target = $target;
        $task->tanggal_selesai = null;
        $task->project_id = $id;
        $task->created_at = now();
        $task->updated_at = now();
        $task->save();

        return redirect('projects/' . $id);
    }

    public function edit($id)
    {
        $task = Task::find($id);
        return view('tasks.edit', compact('task'));
    }

    public function update(Request $request, $id)
    {
        $task = Task::find($id);
        $validasi = $request->validate([
            'nama' => 'required|max:255',
            'keterangan' => 'required',
            'mulai' => 'required',
            'target' => 'required',
        ]);

        $task->nama = $request->nama;
        $task->keterangan = $request->keterangan;
        $task->tanggal_mulai = $request->mulai;
        $task->tanggal_target = $request->target;
        $task->updated_at = now();
        $task->save();

        return redirect('projects/' . $request->id);
    }

    public function destroy($id)
    {
        $task = Task::find($id);
        $task->delete();

        return redirect('projects/' . $task->project_id);
    }

    public function done(Request $request, $id)
    {
        $task = Task::find($id);
        $task->done = 1;
        $task->updated_at = now();
        $task->save();

        return redirect('projects/' . $request->id);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {{-- CSS --}}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{asset('css/bootstrap-datepicker.min.css')}}">
    <title>My Project</title>
</head>
<body>
    <!-- As a heading -->
    <nav class="navbar navbar-dark bg-info">
        <span class="navbar-brand mb-0 mx-5 h1">My Projek</span>
    </nav>

    <div class="container">
        @yield('content')
    </div>


    {{-- JS --}}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{{asset('js/bootstrap-datepicker.min.js')}}"></script>
    <script type="text/javascript">
        $(function(){
         $(".datepicker").datepicker({
             format: 'yyyy-mm-dd',
             autoclose: true,
             todayHighlight: true,
         });
        });
       </script>
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/footer.blade.php
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>

</html>

resources/views/layouts/header.blade.php
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>@yield('title')</title>
</head>

<body>

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2 class="my-4">Create Project</h2>
    <hr>
    <a href="{{route('projects.index')}}" class="btn btn-danger">Kembali</a>
    <div class="row mt-5">
        <div class="col-md-6">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

            <form action="{{route('projects.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="nama">Nama project</label>
                    <input type="text" name="nama" id="nama" class="form-control" placeholder="Nama projek">
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <label for="mulai">Tanggal dimulai</label>
                        <input type="date" name="mulai" id="mulai" class="form-control" placeholder="Dimulai pada">
                    </div>
                    <div class="col-6">
                        <label for="target">Target selesai</label>
                        <input type="date" name="target" id="target" class="form-control" placeholder="Target pada">
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-info">Tambah projek</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2 class="my-4">Update Project</h2>
    <hr>
    <a href="{{url()->previous()}}" class="btn btn-danger">Kembali</a>
    <div class="row mt-5">
        <div class="col-md-6">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

            <form action="{{route('projects.update', $project->id)}}" method="post">
                @method('put')
                @csrf
                <div class="form-group">
                    <label for="nama">Nama project</label>
                <input type="text" name="nama" id="nama" class="form-control" placeholder="Nama projek"  value="{{$project->nama}}">
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <label for="mulai">Tanggal dimulai</label>
                        <input type="date" name="mulai" id="mulai" class="form-control datepicker" placeholder="Dimulai pada" value="{{$project->tanggal_mulai}}">
                    </div>
                    <div class="col-6">
                        <label for="target">Target selesai</label>
                        <input type="date" name="target" id="target" class="form-control datepicker" placeholder="Target pada" value="{{$project->tanggal_target}}">
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-info">Update projek</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2 class="my-4">Projects</h2>
    <hr>
    <a href="{{route('projects.create')}}" class="btn btn-info">Tambah Projek</a>
    <div class="row mt-5">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <th>No</th>
                        <th>Nama projek</th>
                        <th>Dimulai pada</th>
                        <th>Target selesai</th>
                        <th>Selesai pada</th>
                        <th>Terakhir diupdate</th>
                        <th>Aksi</th>
                    </thead>
                    <tbody>
                        @foreach ($projects as $project)
                            <tr>
                            <td>{{$loop->iteration}}</td>
                            <td><a href="{{route('projects.show', $project->id)}}">{{$project->nama}}</a></td>
                            <td>{{$project->tanggal_mulai}}</td>
                            <td>{{$project->tanggal_target}}</td>
                            <td>{{$project->tanggal_selesai}}</td>
                            <td>{{$project->updated_at}}</td>
                            <td>
                                <a href="{{route('projects.edit', $project->id)}}" class="m-1 btn btn-sm btn-success p-1">Sunting</a>
                                <form action="{{route('projects.destroy', $project->id)}}" method="post">
                                    @method('delete')
                                    @csrf
                                <button class="btn btn-danger btn-sm m-1">Hapus</button>
                                </form>
                            </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2 class="my-4">{{$project->nama}}</h2>
    <hr>
    <a href="{{route('projects.index')}}" class="btn btn-danger">Kembali</a>
    <a data-toggle="modal" data-target="#exampleModal" class="btn btn-info">Tambah task</a>
    <div class="row mt-5">
        <div class="col-md-12">
            <h6 class="mx-2">List tasks</h6>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <th>No</th>
                        <th>Nama task</th>
                        <th>Keterangan</th>
                        <th>Target selesai</th>
                        <th>Status</th>
                        <th>Aksi</th>
                    </thead>
                    <tbody>
                        @foreach ($tasks as $task)
                        <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$task->nama}}</td>
                        <td>{{$task->keterangan}}</td>
                        <td>{{$task->tanggal_target}}</td>
                        <td>{{$task->done}}</td>
                        <td>
                            <a href="{{route('tasks.edit', $task->id)}}" class="m-1 btn btn-sm btn-block btn-success p-1">Sunting</a>
                            <form action="{{route('tasks.done', $task->id)}}" method="post">
                                @method('put')
                                @csrf
                                <input type="text" name="id" value="{{$task->project_id}}" hidden>
                            <button class="btn btn-info btn-sm m-1 btn-block">Selesai</button>
                            </form>
                                <form action="{{route('tasks.destroy', $task->id)}}" method="post">
                                    @method('delete')
                                    @csrf
                                <button class="btn btn-danger btn-sm m-1 btn-block">Hapus</button>
                                </form>
                        </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tambah task</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{{route('tasks.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <input type="text" name="id" id="id" class="form-control" placeholder="Nama task" value="<?php echo $project->id; ?>" hidden>
                </div>
                <div class="form-group">
                    <label for="nama">Nama task</label>
                    <input type="text" name="nama" id="nama" class="form-control" placeholder="Nama task">
                </div>
                <div class="form-group">
                    <label for="keterangan">Keterangan</label>
                    <textarea type="text" name="keterangan" id="keterangan" class="form-control" placeholder="Keterangan" rows="3"></textarea>
                </div>

                <div class="form-group row">
                    <div class="col-6">
                        <label for="mulai">Tanggal dimulai</label>
                        <input type="date" name="mulai" id="mulai" class="form-control datepicker" placeholder="Dimulai pada">
                    </div>
                    <div class="col-6">
                        <label for="target">Target selesai</label>
                        <input type="date" name="target" id="target" class="form-control datepicker" placeholder="Target pada">
                    </div>
                </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Tambah</button>
      </form>
      </div>
    </div>
  </div>
</div>

resources/views/tasks/create.blade.php
@extends('layout')

@section('content')
    <h2 class="my-4">Tambah Task</h2>
    <hr>
    <a href="{{url()->previous()}}" class="btn btn-danger">Kembali</a>
    <div class="row mt-5">
        <div class="col-md-6">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

            <form action="{{route('tasks.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="nama">Nama task</label>
                    <input type="text" name="nama" id="nama" class="form-control" placeholder="Nama task">
                </div>
                <div class="form-group">
                    <label for="nama">Nama task</label>
                    <input type="text" name="nama" id="nama" class="form-control" placeholder="Nama task">
                </div>
                <div class="form-group">
                    <label for="keterangan">Keterangan</label>
                    <textarea type="text" name="keterangan" id="keterangan" class="form-control" placeholder="Keterangan" rows="3"></textarea>
                </div>

                <div class="form-group row">
                    <div class="col-6">
                        <label for="mulai">Tanggal dimulai</label>
                        <input type="date" name="mulai" id="mulai" class="form-control datepicker" placeholder="Dimulai pada">
                    </div>
                    <div class="col-6">
                        <label for="target">Target selesai</label>
                        <input type="date" name="target" id="target" class="form-control datepicker" placeholder="Target pada">
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-info">Tambah task</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2 class="my-4">Update Task</h2>
    <hr>
    <a href="{{url()->previous()}}" class="btn btn-danger">Kembali</a>
    <div class="row mt-5">
        <div class="col-md-6">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

            <form action="{{route('tasks.update', $task->id)}}" method="post">
                @method('put')
                @csrf
                <div class="form-group">
                    <input type="text" name="id" id="id" class="form-control" placeholder="Nama task" value="<?php echo $task->project_id; ?>" hidden>
                </div>
                <div class="form-group">
                    <label for="nama">Nama Task</label>
                <input type="text" name="nama" id="nama" class="form-control" placeholder="Nama projek"  value="{{$task->nama}}">
                </div>
                <div class="form-group">
                    <label for="keterangan">Keterangan</label>
                <textarea type="text" name="keterangan" id="keterangan" class="form-control" placeholder="Keterangan" rows="3">{{$task->keterangan}}</textarea>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <label for="mulai">Tanggal dimulai</label>
                        <input type="date" name="mulai" id="mulai" class="form-control datepicker" placeholder="Dimulai pada" value="{{$task->tanggal_mulai}}">
                    </div>
                    <div class="col-6">
                        <label for="target">Target selesai</label>
                        <input type="date" name="target" id="target" class="form-control datepicker" placeholder="Target pada" value="{{$task->tanggal_target}}">
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-info">Update projek</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection